# Generated by Django 2.0.3 on 2018-03-08 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortenurl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls',
            new_name='Url',
        ),
    ]
